import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import './components/footer.module.scss'
import Header from "./components/header.jsx";
import Footer from "./components/footer.jsx";
import './styles/main.scss';
import './styles/_resets.scss';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main>
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
